"use client";

import * as React from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowLeft, ArrowUp, Box, Building2, FileCheck2, Landmark, Pencil, Route, Save, Trash2, Warehouse } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { usePermissions } from "@/hooks/use-permissions";
import { logisticsApi } from "@/modules/logistics/api";
import { LogisticsJobFinance } from "@/modules/logistics/LogisticsJobFinance";
import { LogisticsJobTracking } from "@/modules/logistics/LogisticsJobTracking";
import { LogisticsLegOperations } from "@/modules/logistics/LogisticsLegOperations";
import type { ForwardingJob, LogisticsReferences } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

export default function LogisticsJobDetailPage({ jobId }: { jobId: string }) {
  const id = Number(jobId);
  const { t } = useTranslation();
  const cache = useQueryClient();
  const { hasAnyPermission } = usePermissions();
  const canEdit = hasAnyPermission(["update_logistics_jobs", "manage_logistics"]);
  const canManageParties = hasAnyPermission(["manage_logistics_parties", "manage_logistics"]);
  const canManageCargo = hasAnyPermission(["manage_logistics_cargo", "manage_logistics"]);
  const canManageLegs = hasAnyPermission(["manage_logistics_legs", "manage_logistics"]);
  const canViewCustoms = hasAnyPermission(["view_logistics_customs", "manage_logistics"]);
  const canViewDocuments = hasAnyPermission(["view_logistics_documents", "manage_logistics"]);
  const canViewHandoffs = hasAnyPermission(["view_logistics_warehouse_handoffs", "manage_logistics"]);
  const [notice, setNotice] = React.useState("");
  const jobQuery = useQuery({ queryKey: ["logistics", "job", id], queryFn: () => logisticsApi.job(id).then((response) => response.data.data as ForwardingJob), enabled: Number.isInteger(id) });
  const refsQuery = useQuery({ queryKey: ["logistics", "references"], queryFn: () => logisticsApi.references().then((response) => response.data.data as LogisticsReferences) });
  const refresh = async (message: string) => { await cache.invalidateQueries({ queryKey: ["logistics", "job", id] }); setNotice(message); };
  const errorMessage = (error: unknown) => (error as { response?: { data?: { message?: string; errors?: Record<string, string[]> } } }).response?.data?.message ?? t("logistics.errors.save", "The change could not be saved.");
  const [error, setError] = React.useState("");

  const updateJob = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.updateJob(id, payload), onSuccess: async (response) => { if (response.status === 202) setNotice(t("logistics.messages.awaiting_approval", "The change is waiting for workflow approval.")); else await refresh(t("logistics.messages.saved", "Job updated.")); }, onError: (value) => setError(errorMessage(value)) });
  const addParty = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.addParty(id, payload), onSuccess: () => refresh(t("logistics.messages.party_added", "Shipment party added.")), onError: (value) => setError(errorMessage(value)) });
  const addCargo = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.addCargo(id, payload), onSuccess: () => refresh(t("logistics.messages.cargo_added", "Cargo line added.")), onError: (value) => setError(errorMessage(value)) });
  const addPackage = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.addPackage(id, payload), onSuccess: () => refresh(t("logistics.messages.package_added", "Package added.")), onError: (value) => setError(errorMessage(value)) });
  const addLeg = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.addLeg(id, payload), onSuccess: () => refresh(t("logistics.messages.leg_added", "Transport leg added.")), onError: (value) => setError(errorMessage(value)) });
  const reviseLeg = useMutation({ mutationFn: ({ legId, payload }: { legId: number; payload: Record<string, unknown> }) => logisticsApi.reviseLeg(id, legId, payload), onSuccess: () => refresh(t("logistics.messages.leg_revised", "A new route revision was created.")), onError: (value) => setError(errorMessage(value)) });
  const reorderLegs = useMutation({ mutationFn: (legIds: number[]) => logisticsApi.reorderLegs(id, legIds), onSuccess: () => refresh(t("logistics.messages.legs_reordered", "The route was reordered as a new revision.")), onError: (value) => setError(errorMessage(value)) });
  const removeLeg = useMutation({ mutationFn: (legId: number) => logisticsApi.removeLeg(id, legId), onSuccess: () => refresh(t("logistics.messages.leg_removed", "The draft leg was removed in a new route revision.")), onError: (value) => setError(errorMessage(value)) });
  const job = jobQuery.data;
  const refs = refsQuery.data;
  const moveLeg = (index: number, direction: -1 | 1) => {
    const ordered = [...(job?.legs ?? [])];
    const target = index + direction;
    if (!ordered[index] || !ordered[target]) return;
    [ordered[index], ordered[target]] = [ordered[target], ordered[index]];
    setError(""); setNotice(""); reorderLegs.mutate(ordered.map((leg) => leg.id));
  };
  const localDateTime = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

  const submitForm = (event: React.FormEvent<HTMLFormElement>, mutate: (payload: Record<string, unknown>) => void, fields: string[]) => {
    event.preventDefault(); setError(""); setNotice("");
    const data = new FormData(event.currentTarget); const payload: Record<string, unknown> = {};
    fields.forEach((field) => { const value = data.get(field); payload[field] = field.endsWith("_id") || field === "pieces" || field === "quantity" ? (value ? Number(value) : null) : value; });
    mutate(payload);
  };

  if (jobQuery.isLoading) return <p role="status">{t("logistics.loading", "Loading logistics operations…")}</p>;
  if (jobQuery.isError || !job) return <p role="alert" className="text-destructive">{t("logistics.errors.job", "This forwarding job could not be loaded.")}</p>;

  return <main className="space-y-6">
    <header><Link href="/dashboard/logistics/jobs" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-teal-700 hover:underline dark:text-teal-300"><ArrowLeft aria-hidden="true" className="h-4 w-4" />{t("logistics.actions.back_jobs", "Back to forwarding jobs")}</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="font-mono text-3xl font-black tracking-tight">{job.job_number}</h1><span className="rounded-full bg-teal-950 px-3 py-1 text-xs font-semibold text-teal-50">{t(`logistics.status.${job.status}`, job.status.replaceAll("_", " "))}</span></div><p className="mt-1 text-sm text-muted-foreground">{job.customer?.name} · {job.origin_node?.name} → {job.destination_node?.name}</p></header>
    <div aria-live="polite">{notice ? <p className="rounded-xl border border-teal-700/30 bg-teal-50 p-4 text-teal-950 dark:bg-teal-950 dark:text-teal-50">{notice}</p> : null}{error ? <p role="alert" className="rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-destructive">{error}</p> : null}</div>
    <section aria-labelledby="job-overview-heading" className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="job-overview-heading" className="text-lg font-bold">{t("logistics.detail.overview", "Job overview")}</h2><span className="text-xs text-muted-foreground">{t("logistics.detail.version", "Record version")} {job.lock_version}</span></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.customer", "Customer")}</dt><dd className="mt-1 font-semibold">{job.customer?.name}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.responsible", "Responsible employee")}</dt><dd className="mt-1 font-semibold">{job.responsible_employee?.primary_name ?? "—"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.departure", "Planned departure")}</dt><dd className="mt-1 font-semibold">{job.planned_departure_at ? new Date(job.planned_departure_at).toLocaleString() : "—"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.arrival", "Planned arrival")}</dt><dd className="mt-1 font-semibold">{job.planned_arrival_at ? new Date(job.planned_arrival_at).toLocaleString() : "—"}</dd></div></dl>
      {canEdit ? <form className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-[14rem_minmax(14rem,1fr)_auto]" onSubmit={(event) => submitForm(event, (payload) => updateJob.mutate({ ...payload, lock_version: job.lock_version }), ["status", "internal_notes"])}><div><Label htmlFor="detail-status">{t("logistics.fields.status", "Status")}</Label><NativeSelect id="detail-status" name="status" defaultValue={job.status} className="mt-1 min-h-11 w-full">{["draft", "planned", "active", "in_transit", "arrived", "completed", "cancelled"].map((value) => <option key={value} value={value}>{t(`logistics.status.${value}`, value.replaceAll("_", " "))}</option>)}</NativeSelect></div><div><Label htmlFor="detail-notes">{t("logistics.fields.notes", "Internal notes")}</Label><Input id="detail-notes" name="internal_notes" defaultValue={job.internal_notes ?? ""} className="mt-1 min-h-11" /></div><Button type="submit" className="min-h-11 self-end" disabled={updateJob.isPending}><Save aria-hidden="true" />{t("common.save", "Save")}</Button></form> : null}
    </section>
    <section aria-labelledby="shipment-parties-heading" className="rounded-2xl border bg-card p-5"><h2 id="shipment-parties-heading" className="flex items-center gap-2 text-lg font-bold"><Building2 aria-hidden="true" className="text-teal-700" />{t("logistics.detail.parties", "Shipment parties")}</h2><ul className="mt-4 grid gap-3 md:grid-cols-2">{job.parties?.map((party) => <li key={String(party.id)} className="rounded-xl border p-4"><p className="font-semibold">{String(party.legal_name)}</p><p className="text-sm text-muted-foreground">{t(`logistics.roles.${String(party.role)}`, String(party.role).replaceAll("_", " "))}</p></li>)}</ul>{canManageParties ? <details className="mt-4 rounded-xl border p-4"><summary className="min-h-11 cursor-pointer content-center font-semibold">{t("logistics.actions.add_party", "Add shipment party")}</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={(event) => submitForm(event, addParty.mutate, ["role", "legal_name", "contact_name", "email"])}><div><Label htmlFor="party-role">{t("logistics.fields.role", "Role")}</Label><NativeSelect id="party-role" name="role" required className="mt-1 min-h-11 w-full">{["shipper", "consignee", "notify_party", "carrier", "customs_broker", "other"].map((value) => <option key={value} value={value}>{t(`logistics.roles.${value}`, value.replaceAll("_", " "))}</option>)}</NativeSelect></div><div><Label htmlFor="party-name">{t("logistics.fields.legal_name", "Legal name")}</Label><Input id="party-name" name="legal_name" required className="mt-1 min-h-11" /></div><div><Label htmlFor="party-contact">{t("logistics.fields.contact", "Contact name")}</Label><Input id="party-contact" name="contact_name" className="mt-1 min-h-11" /></div><div><Label htmlFor="party-email">{t("logistics.fields.email", "Email")}</Label><Input id="party-email" name="email" type="email" className="mt-1 min-h-11" /></div><Button type="submit" className="min-h-11 sm:col-span-2 sm:justify-self-end" disabled={addParty.isPending}>{t("logistics.actions.add_party", "Add shipment party")}</Button></form></details> : null}</section>
    <section aria-labelledby="cargo-heading" className="rounded-2xl border bg-card p-5"><h2 id="cargo-heading" className="flex items-center gap-2 text-lg font-bold"><Box aria-hidden="true" className="text-teal-700" />{t("logistics.detail.cargo", "Cargo")}</h2><ul className="mt-4 divide-y">{job.cargo?.map((cargo) => <li key={String(cargo.id)} className="flex justify-between gap-4 py-3"><span>{String(cargo.description)}</span><span className="text-sm text-muted-foreground">{String(cargo.pieces)} {t("logistics.units.pieces", "piece(s)")}</span></li>)}</ul>{canManageCargo ? <details className="mt-4 rounded-xl border p-4"><summary className="min-h-11 cursor-pointer content-center font-semibold">{t("logistics.actions.add_cargo", "Add cargo line")}</summary><form className="mt-3 grid gap-3 sm:grid-cols-[1fr_10rem_auto]" onSubmit={(event) => submitForm(event, addCargo.mutate, ["description", "pieces", "gross_weight"])}><div><Label htmlFor="cargo-description">{t("logistics.fields.description", "Description")}</Label><Input id="cargo-description" name="description" required className="mt-1 min-h-11" /></div><div><Label htmlFor="cargo-pieces">{t("logistics.fields.pieces", "Pieces")}</Label><Input id="cargo-pieces" name="pieces" type="number" min="1" defaultValue="1" required className="mt-1 min-h-11" /></div><div><Label htmlFor="cargo-weight">{t("logistics.fields.weight", "Gross kg")}</Label><Input id="cargo-weight" name="gross_weight" type="number" min="0" step="0.001" className="mt-1 min-h-11" /></div><Button type="submit" className="min-h-11 sm:col-span-3 sm:justify-self-end" disabled={addCargo.isPending}>{t("logistics.actions.add_cargo", "Add cargo line")}</Button></form></details> : null}</section>
    <section aria-labelledby="packages-heading" className="rounded-2xl border bg-card p-5"><h2 id="packages-heading" className="flex items-center gap-2 text-lg font-bold"><Box aria-hidden="true" className="text-teal-700" />{t("logistics.detail.packages", "Packages")}</h2><ul className="mt-4 divide-y">{job.packages?.map((item) => <li key={String(item.id)} className="flex justify-between gap-4 py-3"><span>{String(item.package_type)}</span><span className="text-sm text-muted-foreground">{String(item.quantity)} {t("logistics.units.packages", "package(s)")}</span></li>)}</ul>{canManageCargo ? <details className="mt-4 rounded-xl border p-4"><summary className="min-h-11 cursor-pointer content-center font-semibold">{t("logistics.actions.add_package", "Add package")}</summary><form className="mt-3 grid gap-3 sm:grid-cols-[1fr_10rem_1fr_auto]" onSubmit={(event) => submitForm(event, addPackage.mutate, ["package_type", "quantity", "cargo_id", "marks_and_numbers"])}><div><Label htmlFor="package-type">{t("logistics.fields.package_type", "Package type")}</Label><Input id="package-type" name="package_type" required placeholder={t("logistics.placeholders.package_type", "Carton, pallet, crate…")} className="mt-1 min-h-11" /></div><div><Label htmlFor="package-quantity">{t("logistics.fields.quantity", "Quantity")}</Label><Input id="package-quantity" name="quantity" type="number" min="1" defaultValue="1" required className="mt-1 min-h-11" /></div><div><Label htmlFor="package-cargo">{t("logistics.fields.cargo_line", "Cargo line")}</Label><NativeSelect id="package-cargo" name="cargo_id" className="mt-1 min-h-11 w-full"><option value="">{t("logistics.optional.none", "Not linked")}</option>{job.cargo?.map((cargo) => <option key={String(cargo.id)} value={String(cargo.id)}>{String(cargo.description)}</option>)}</NativeSelect></div><div><Label htmlFor="package-marks">{t("logistics.fields.marks", "Marks / numbers")}</Label><Input id="package-marks" name="marks_and_numbers" className="mt-1 min-h-11" /></div><Button type="submit" className="min-h-11 sm:col-span-4 sm:justify-self-end" disabled={addPackage.isPending}>{t("logistics.actions.add_package", "Add package")}</Button></form></details> : null}</section>
    <section aria-labelledby="bookings-heading" className="rounded-2xl border bg-card p-5">
      <h2 id="bookings-heading" className="text-lg font-bold">{t("logistics.bookings.title", "Bookings")}</h2>
      {job.bookings?.length ? <ul className="mt-4 grid gap-3 md:grid-cols-2">{job.bookings.map((booking) => <li key={booking.id} className="rounded-xl border p-4"><Link href={"/dashboard/logistics/bookings/" + booking.id} className="font-mono font-semibold text-primary hover:underline">{booking.booking_number}</Link><p className="mt-1 text-sm text-muted-foreground">{booking.provider?.name ?? t("logistics.optional.any_provider", "Any provider")} · {t("logistics.status." + booking.status, booking.status.replaceAll("_", " "))}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.job_bookings", "No booking is linked to this job.")}</p>}
    </section>
    {canViewCustoms || canViewDocuments || canViewHandoffs ? <section aria-labelledby="job-compliance-heading" className="rounded-2xl border bg-card p-5"><h2 id="job-compliance-heading" className="text-lg font-bold">{t("logistics.detail.compliance", "Customs, documents, and warehouse")}</h2><div className="mt-4 grid gap-4 lg:grid-cols-3">
      {canViewCustoms ? <div className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Landmark aria-hidden="true" className="text-primary" />{t("logistics.customs.title", "Customs cases")}</h3>{job.customs_cases?.length ? <ul className="mt-3 space-y-2">{job.customs_cases.map((item) => <li key={item.id}><Link className="inline-flex min-h-11 items-center font-mono text-primary hover:underline" href={`/dashboard/logistics/customs/${item.id}`}>{item.case_number}</Link><p className="text-xs text-muted-foreground">{t(`logistics.status.${item.status}`, item.status.replaceAll("_", " "))}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.job_customs", "No customs case is linked to this job.")}</p>}</div> : null}
      {canViewDocuments ? <div className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><FileCheck2 aria-hidden="true" className="text-primary" />{t("logistics.documents.title", "Freight documents")}</h3>{job.freight_documents?.length ? <ul className="mt-3 space-y-2">{job.freight_documents.map((item) => <li key={item.id}><Link className="inline-flex min-h-11 items-center font-mono text-primary hover:underline" href={`/dashboard/logistics/documents/${item.id}`}>{item.document_number ?? item.document_record_number}</Link><p className="text-xs text-muted-foreground">{item.type?.name ?? "—"} · {t(`logistics.status.${item.status}`, item.status)}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.job_documents", "No freight document is linked to this job.")}</p>}</div> : null}
      {canViewHandoffs ? <div className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Warehouse aria-hidden="true" className="text-primary" />{t("logistics.warehouse_handoffs.title", "Warehouse handoffs")}</h3>{job.warehouse_handoffs?.length ? <ul className="mt-3 space-y-2">{job.warehouse_handoffs.map((item) => <li key={item.id}><Link className="inline-flex min-h-11 items-center font-mono text-primary hover:underline" href={`/dashboard/logistics/warehouse-handoffs/${item.id}`}>{item.handoff_number}</Link><p className="text-xs text-muted-foreground">{t(`logistics.handoff_purpose.${item.purpose}`, item.purpose)} · {t(`logistics.status.${item.status}`, item.status)}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.job_handoffs", "No warehouse handoff is linked to this job.")}</p>}</div> : null}
    </div></section> : null}
    <section aria-labelledby="route-heading" className="rounded-2xl border bg-card p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="route-heading" className="flex items-center gap-2 text-lg font-bold"><Route aria-hidden="true" className="text-teal-700" />{t("logistics.route.builder_title", "Multimodal route builder")}</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{t("logistics.route.builder_description", "Add and revise ordered transport legs.")}</p></div><span className="font-mono text-xs">{t("logistics.detail.revision", "Revision")} {job.current_route_revision}</span></div>
      {job.legs?.length ? <ol className="mt-5 space-y-3">{job.legs.map((leg, index) => <li key={leg.id} className="grid grid-cols-[2.5rem_minmax(0,1fr)] gap-3 rounded-xl border p-4">
        <span className="grid h-9 w-9 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{leg.sequence}</span>
        <div className="min-w-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{leg.origin_node?.name ?? leg.origin_node_id} → {leg.destination_node?.name ?? leg.destination_node_id}</p><p className="text-sm text-muted-foreground">{leg.transport_mode?.name ?? ""}{leg.provider?.name ? " · " + leg.provider.name : ""}{leg.service_type ? " · " + leg.service_type : ""}</p>{leg.planned_departure_at || leg.planned_arrival_at ? <p className="mt-1 text-xs text-muted-foreground">{leg.planned_departure_at ? new Date(leg.planned_departure_at).toLocaleString() : "—"} → {leg.planned_arrival_at ? new Date(leg.planned_arrival_at).toLocaleString() : "—"}</p> : null}</div>
        {canManageLegs ? <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="icon" className="min-h-11 min-w-11" aria-label={t("logistics.actions.move_leg_up", "Move leg up") + " " + leg.sequence} disabled={index === 0 || reorderLegs.isPending} onClick={() => moveLeg(index, -1)}><ArrowUp aria-hidden="true" /></Button><Button type="button" variant="outline" size="icon" className="min-h-11 min-w-11" aria-label={t("logistics.actions.move_leg_down", "Move leg down") + " " + leg.sequence} disabled={index === (job.legs?.length ?? 0) - 1 || reorderLegs.isPending} onClick={() => moveLeg(index, 1)}><ArrowDown aria-hidden="true" /></Button>{leg.status === "planned" ? <Button type="button" variant="outline" size="icon" className="min-h-11 min-w-11 text-destructive" aria-label={t("logistics.actions.remove_leg", "Remove leg") + " " + leg.sequence} disabled={removeLeg.isPending} onClick={() => removeLeg.mutate(leg.id)}><Trash2 aria-hidden="true" /></Button> : null}</div> : null}</div>
        <LogisticsLegOperations jobId={id} leg={leg} refs={refs} onChanged={async () => { await cache.invalidateQueries({ queryKey: ["logistics", "job", id] }); }} />
        {canManageLegs && leg.status === "planned" ? <details className="mt-3 rounded-lg border p-3"><summary className="flex min-h-11 cursor-pointer items-center gap-2 font-semibold"><Pencil aria-hidden="true" className="h-4 w-4" />{t("logistics.actions.revise_leg", "Revise leg")}</summary><form className="mt-3 grid gap-3 md:grid-cols-3" onSubmit={(event) => submitForm(event, (payload) => reviseLeg.mutate({ legId: leg.id, payload }), ["transport_mode_id", "origin_node_id", "destination_node_id", "provider_supplier_id", "service_type", "planned_departure_at", "planned_arrival_at", "provider_reference", "notes"])}>
          <div><Label htmlFor={"revise-" + leg.id + "-mode"}>{t("logistics.fields.mode", "Mode")}</Label><NativeSelect id={"revise-" + leg.id + "-mode"} name="transport_mode_id" required defaultValue={leg.transport_mode_id} className="mt-1 min-h-11 w-full">{refs?.modes.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</NativeSelect></div>
          <div><Label htmlFor={"revise-" + leg.id + "-origin"}>{t("logistics.fields.origin", "Origin")}</Label><NativeSelect id={"revise-" + leg.id + "-origin"} name="origin_node_id" required defaultValue={leg.origin_node_id} className="mt-1 min-h-11 w-full">{refs?.nodes.map((option) => <option key={option.id} value={option.id}>{option.code} — {option.name}</option>)}</NativeSelect></div>
          <div><Label htmlFor={"revise-" + leg.id + "-destination"}>{t("logistics.fields.destination", "Destination")}</Label><NativeSelect id={"revise-" + leg.id + "-destination"} name="destination_node_id" required defaultValue={leg.destination_node_id} className="mt-1 min-h-11 w-full">{refs?.nodes.map((option) => <option key={option.id} value={option.id}>{option.code} — {option.name}</option>)}</NativeSelect></div>
          <div><Label htmlFor={"revise-" + leg.id + "-provider"}>{t("logistics.fields.provider", "Provider")}</Label><NativeSelect id={"revise-" + leg.id + "-provider"} name="provider_supplier_id" defaultValue={leg.provider_supplier_id ?? ""} className="mt-1 min-h-11 w-full"><option value="">{t("logistics.optional.any_provider", "Any provider")}</option>{refs?.suppliers.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</NativeSelect></div>
          <div><Label htmlFor={"revise-" + leg.id + "-service"}>{t("logistics.fields.service", "Service")}</Label><Input id={"revise-" + leg.id + "-service"} name="service_type" defaultValue={leg.service_type ?? ""} className="mt-1 min-h-11" /></div>
          <div><Label htmlFor={"revise-" + leg.id + "-reference"}>{t("logistics.fields.provider_reference", "Provider reference")}</Label><Input id={"revise-" + leg.id + "-reference"} name="provider_reference" defaultValue={leg.provider_reference ?? ""} className="mt-1 min-h-11" /></div>
          <div><Label htmlFor={"revise-" + leg.id + "-departure"}>{t("logistics.fields.departure", "Planned departure")}</Label><Input id={"revise-" + leg.id + "-departure"} name="planned_departure_at" type="datetime-local" defaultValue={localDateTime(leg.planned_departure_at)} className="mt-1 min-h-11" /></div>
          <div><Label htmlFor={"revise-" + leg.id + "-arrival"}>{t("logistics.fields.arrival", "Planned arrival")}</Label><Input id={"revise-" + leg.id + "-arrival"} name="planned_arrival_at" type="datetime-local" defaultValue={localDateTime(leg.planned_arrival_at)} className="mt-1 min-h-11" /></div>
          <div><Label htmlFor={"revise-" + leg.id + "-notes"}>{t("logistics.fields.notes", "Notes")}</Label><Input id={"revise-" + leg.id + "-notes"} name="notes" defaultValue={leg.notes ?? ""} className="mt-1 min-h-11" /></div>
          <Button type="submit" className="min-h-11 md:col-span-3 md:justify-self-end" disabled={reviseLeg.isPending}>{t("logistics.actions.revise_leg", "Revise leg")}</Button>
        </form></details> : null}</div>
      </li>)}</ol> : <p className="mt-4 text-sm text-muted-foreground">{t("logistics.empty.route", "No transport legs have been added.")}</p>}
      {canManageLegs ? <details className="mt-4 rounded-xl border p-4"><summary className="min-h-11 cursor-pointer content-center font-semibold">{t("logistics.actions.add_leg", "Add transport leg")}</summary><form className="mt-3 grid gap-3 md:grid-cols-3" onSubmit={(event) => submitForm(event, addLeg.mutate, ["transport_mode_id", "origin_node_id", "destination_node_id", "provider_supplier_id", "service_type", "planned_departure_at", "planned_arrival_at"])}>
        <div><Label htmlFor="leg-mode">{t("logistics.fields.mode", "Mode")}</Label><NativeSelect id="leg-mode" name="transport_mode_id" required className="mt-1 min-h-11 w-full">{refs?.modes.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</NativeSelect></div>
        <div><Label htmlFor="leg-origin">{t("logistics.fields.origin", "Origin")}</Label><NativeSelect id="leg-origin" name="origin_node_id" required className="mt-1 min-h-11 w-full">{refs?.nodes.map((option) => <option key={option.id} value={option.id}>{option.code} — {option.name}</option>)}</NativeSelect></div>
        <div><Label htmlFor="leg-destination">{t("logistics.fields.destination", "Destination")}</Label><NativeSelect id="leg-destination" name="destination_node_id" required className="mt-1 min-h-11 w-full">{refs?.nodes.map((option) => <option key={option.id} value={option.id}>{option.code} — {option.name}</option>)}</NativeSelect></div>
        <div><Label htmlFor="leg-provider">{t("logistics.fields.provider", "Provider")}</Label><NativeSelect id="leg-provider" name="provider_supplier_id" className="mt-1 min-h-11 w-full"><option value="">{t("logistics.optional.any_provider", "Any provider")}</option>{refs?.suppliers.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</NativeSelect></div>
        <div><Label htmlFor="leg-service">{t("logistics.fields.service", "Service")}</Label><Input id="leg-service" name="service_type" className="mt-1 min-h-11" /></div>
        <div><Label htmlFor="leg-departure">{t("logistics.fields.departure", "Planned departure")}</Label><Input id="leg-departure" name="planned_departure_at" type="datetime-local" className="mt-1 min-h-11" /></div>
        <div><Label htmlFor="leg-arrival">{t("logistics.fields.arrival", "Planned arrival")}</Label><Input id="leg-arrival" name="planned_arrival_at" type="datetime-local" className="mt-1 min-h-11" /></div>
        <Button type="submit" className="min-h-11 self-end" disabled={addLeg.isPending}>{t("logistics.actions.add_leg", "Add transport leg")}</Button>
      </form></details> : null}
    </section>
    <LogisticsJobTracking jobId={id} />
    <LogisticsJobFinance jobId={id} refs={refs} />
    <section aria-labelledby="activity-heading" className="rounded-2xl border bg-card p-5"><h2 id="activity-heading" className="text-lg font-bold">{t("logistics.detail.activity", "Activity")}</h2>{job.activity?.length ? <ol className="mt-4 space-y-3">{job.activity.map((item) => <li key={item.id} className="border-l-2 border-teal-700 pl-4"><p className="font-medium">{item.description}</p><time className="text-xs text-muted-foreground" dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></li>)}</ol> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.activity", "No recorded changes yet.")}</p>}</section>
  </main>;
}
