"use client";

import { FormEvent } from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertOctagon, ArrowLeft, MessageSquare, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { logisticsApi } from "@/modules/logistics/api";
import type { LogisticsException, LogisticsReferences } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

export default function LogisticsExceptionDetailPage({ exceptionId }: { exceptionId: string }) {
  const id = Number(exceptionId);
  const { t } = useTranslation();
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["logistics", "exception", id], queryFn: () => logisticsApi.exception(id).then((response) => response.data as LogisticsException) });
  const refs = useQuery({ queryKey: ["logistics", "references"], queryFn: () => logisticsApi.references().then((response) => response.data.data as LogisticsReferences) });
  const refresh = () => client.invalidateQueries({ queryKey: ["logistics", "exception", id] });
  const transition = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.transitionException(id, payload), onSuccess: refresh });
  const assign = useMutation({ mutationFn: (employeeId: number | null) => logisticsApi.assignException(id, employeeId), onSuccess: refresh });
  const comment = useMutation({ mutationFn: (value: string) => logisticsApi.commentOnException(id, value), onSuccess: refresh });
  const item = query.data;
  if (query.isLoading) return <p role="status">{t("logistics.loading", "Loading logistics operations…")}</p>;
  if (query.isError || !item) return <p role="alert" className="text-destructive">{t("logistics.errors.exception", "This operational exception could not be loaded.")}</p>;
  const submitTransition = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); transition.mutate({ status: form.get("status"), resolution: form.get("resolution") || undefined }); };
  const submitComment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); comment.mutate(String(data.get("comment") ?? ""), { onSuccess: () => form.reset() }); };
  return <main className="space-y-6">
    <header><Link href="/dashboard/logistics/exceptions" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-teal-700 hover:underline dark:text-teal-300"><ArrowLeft aria-hidden="true" />{t("logistics.actions.back_exceptions", "Back to exceptions")}</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="font-mono text-3xl font-black">{item.exception_number}</h1><span className="rounded-full border border-border px-3 py-1 text-xs font-bold">{t(`logistics.severity.${item.severity}`, item.severity)}</span><span className="rounded-full bg-teal-950 px-3 py-1 text-xs font-semibold text-teal-50">{t(`logistics.status.${item.status}`, item.status.replaceAll("_", " "))}</span></div><p className="mt-1 text-sm text-muted-foreground">{item.job?.job_number} · {t(`logistics.exception_labels.${item.category}`, item.category.replaceAll("_", " "))}</p></header>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section aria-labelledby="exception-context" className="rounded-2xl border border-border/70 bg-card p-5"><h2 id="exception-context" className="flex items-center gap-2 text-lg font-bold"><AlertOctagon aria-hidden="true" className="text-red-700 dark:text-red-300" />{t("logistics.exceptions.context", "Exception context")}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.action_required", "Action required")}</dt><dd className="mt-1 font-medium">{item.action_required}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.operational_impact", "Operational impact")}</dt><dd className="mt-1 font-medium">{item.operational_impact ?? "—"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.customer_impact", "Customer impact")}</dt><dd className="mt-1 font-medium">{item.customer_impact ?? "—"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted-foreground">{t("logistics.fields.root_cause", "Root cause")}</dt><dd className="mt-1 font-medium">{item.root_cause_detail ?? item.root_cause_code ?? "—"}</dd></div></dl></section>
      <section aria-labelledby="exception-owner" className="rounded-2xl border border-border/70 bg-card p-5"><h2 id="exception-owner" className="text-lg font-bold">{t("logistics.exceptions.ownership", "Ownership and state")}</h2><Label htmlFor="exception-assignee" className="mt-4 block">{t("logistics.fields.responsible", "Responsible employee")}</Label><NativeSelect id="exception-assignee" value={item.responsible_employee_id ?? ""} onChange={(event) => assign.mutate(event.target.value ? Number(event.target.value) : null)} className="mt-1 min-h-11 w-full"><option value="">{t("logistics.select.employee", "Unassigned")}</option>{refs.data?.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.primary_name ?? employee.name}</option>)}</NativeSelect><form onSubmit={submitTransition} className="mt-5 space-y-3"><div><Label htmlFor="exception-transition">{t("logistics.fields.status", "Status")}</Label><NativeSelect id="exception-transition" name="status" defaultValue={item.status} className="mt-1 min-h-11 w-full">{["acknowledged", "in_progress", "waiting_external", "escalated", "resolved", "closed"].map((value) => <option key={value} value={value}>{t(`logistics.status.${value}`, value.replaceAll("_", " "))}</option>)}</NativeSelect></div><div><Label htmlFor="exception-resolution">{t("logistics.fields.resolution", "Resolution")}</Label><Textarea id="exception-resolution" name="resolution" defaultValue={item.resolution ?? ""} className="mt-1" /></div><Button type="submit" disabled={transition.isPending} className="min-h-11"><Save aria-hidden="true" />{t("logistics.actions.update_exception", "Update exception")}</Button></form></section></div>
    <section aria-labelledby="exception-comments" className="rounded-2xl border border-border/70 bg-card p-5"><h2 id="exception-comments" className="flex items-center gap-2 text-lg font-bold"><MessageSquare aria-hidden="true" />{t("logistics.exceptions.comments", "Resolution timeline")}</h2>{item.comments?.length ? <ol className="mt-4 space-y-3">{item.comments.map((entry) => <li key={entry.id} className="border-l-2 border-teal-600 pl-4"><p>{entry.comment}</p><p className="mt-1 text-xs text-muted-foreground">{entry.created_by?.name ?? "—"} · {new Date(entry.created_at).toLocaleString()}</p></li>)}</ol> : <p className="mt-3 text-sm text-muted-foreground">{t("logistics.empty.comments", "No investigation comments yet.")}</p>}<form onSubmit={submitComment} className="mt-5"><Label htmlFor="exception-comment">{t("logistics.fields.comment", "Comment")}</Label><Textarea id="exception-comment" name="comment" required className="mt-1" /><Button type="submit" disabled={comment.isPending} className="mt-3 min-h-11">{t("logistics.actions.add_comment", "Add comment")}</Button></form></section>
  </main>;
}
