"use client";

import Link from "next/link";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Combine, Plus, Trash2 } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { usePermissions } from "@/hooks/use-permissions";
import { logisticsApi } from "@/modules/logistics/api";
import type { Consolidation, ForwardingJob } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

export default function LogisticsConsolidationDetailPage({consolidationId}:{consolidationId:string}){
  const id=Number(consolidationId);const{t}=useTranslation();const cache=useQueryClient();const{hasAnyPermission}=usePermissions();
  const canUpdate=hasAnyPermission(["update_logistics_consolidations","manage_logistics"]);const canConfirm=hasAnyPermission(["confirm_logistics_consolidations","manage_logistics"]);const canDeconsolidate=hasAnyPermission(["deconsolidate_logistics_consolidations","manage_logistics"]);
  const[notice,setNotice]=React.useState("");const[error,setError]=React.useState("");
  const query=useQuery({queryKey:["logistics","consolidation",id],queryFn:()=>logisticsApi.consolidation(id).then((response)=>response.data.data as Consolidation),enabled:Number.isInteger(id)});
  const jobs=useQuery({queryKey:["logistics","jobs","consolidation-members"],queryFn:()=>logisticsApi.jobs({per_page:100}).then((response)=>(response.data.data??[]) as ForwardingJob[])});
  const refresh=async(message:string)=>{await cache.invalidateQueries({queryKey:["logistics","consolidation",id]});setError("");setNotice(message);};const fail=(value:unknown)=>setError((value as {response?:{data?:{message?:string}}}).response?.data?.message??t("logistics.errors.consolidation_save"));
  const add=useMutation({mutationFn:(payload:Record<string,unknown>)=>logisticsApi.addConsolidationMember(id,payload),onSuccess:()=>refresh(t("logistics.messages.consolidation_member_added")),onError:fail});
  const remove=useMutation({mutationFn:(memberId:number)=>logisticsApi.removeConsolidationMember(id,memberId),onSuccess:()=>refresh(t("logistics.messages.consolidation_member_removed")),onError:fail});
  const transition=useMutation({mutationFn:(status:string)=>logisticsApi.transitionConsolidation(id,status),onSuccess:(_,status)=>refresh(t(`logistics.status.${status}`,status.replaceAll("_"," "))),onError:fail});
  const item=query.data;
  if(query.isLoading)return <p role="status" className="flex items-center gap-2"><Spinner/>{t("logistics.loading")}</p>;
  if(query.isError||!item)return <Alert variant="destructive"><AlertTitle>{t("logistics.errors.load_title")}</AlertTitle><AlertDescription>{t("logistics.errors.consolidations")}</AlertDescription></Alert>;
  const memberIds=new Set(item.members?.map((member)=>member.house_forwarding_job_id));
  return <main className="space-y-6"><header><Link href="/dashboard/logistics/consolidations" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary hover:underline"><ArrowLeft aria-hidden="true"/>{t("logistics.actions.back_consolidations")}</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="font-mono text-3xl font-black tracking-tight">{item.consolidation_number}</h1><Badge>{t(`logistics.status.${item.status}`,item.status.replaceAll("_"," "))}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.origin_node?.name} → {item.destination_node?.name} · {item.mode?.name}</p></header>
  <div aria-live="polite">{notice?<Alert><AlertTitle>{notice}</AlertTitle></Alert>:null}{error?<Alert variant="destructive"><AlertTitle>{t("logistics.errors.action_title")}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>:null}</div>
  <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><Combine aria-hidden="true"/>{t("logistics.consolidations.movement")}</CardTitle><CardDescription>{item.master_reference??item.consolidation_number}</CardDescription></div><div className="flex flex-wrap gap-2">{canConfirm&&["draft","building","ready"].includes(item.status)?<Button type="button" disabled={transition.isPending} onClick={()=>transition.mutate(item.status==="draft"?"building":item.status==="building"?"ready":"confirmed")}>{item.status==="ready"?t("logistics.actions.confirm_consolidation"):t(`logistics.status.${item.status==="draft"?"building":"ready"}`,item.status==="draft"?"Building":"Ready")}</Button>:null}{canDeconsolidate&&item.status==="arrived"?<Button type="button" onClick={()=>transition.mutate("deconsolidating")}>{t("logistics.actions.start_deconsolidation")}</Button>:null}{canDeconsolidate&&item.status==="deconsolidating"?<Button type="button" onClick={()=>transition.mutate("completed")}>{t("logistics.actions.complete_consolidation")}</Button>:null}</div></div></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label={t("logistics.fields.master_job")} value={item.master_job?.job_number??t("logistics.consolidations.no_master_job")}/><Info label={t("logistics.fields.provider")} value={item.provider?.name??t("logistics.optional.any_provider")}/><Info label={t("logistics.fields.allocation_method")} value={t(`logistics.allocation.${item.allocation_method}`)}/><Info label={t("logistics.fields.departure")} value={item.planned_departure_at?new Date(item.planned_departure_at).toLocaleString():"—"}/><Info label={t("logistics.fields.capacity_weight")} value={item.capacity_weight_kg??"—"}/><Info label={t("logistics.fields.capacity_cbm")} value={item.capacity_cbm??"—"}/><Info label={t("logistics.fields.capacity_packages")} value={item.capacity_packages??"—"}/><Info label={t("logistics.fields.members")} value={String(item.members?.length??0)}/></dl></CardContent></Card>
  <Card><CardHeader><CardTitle>{t("logistics.consolidations.members")}</CardTitle><CardDescription>{t("logistics.consolidations.capacity")}</CardDescription></CardHeader><CardContent className="space-y-4">{canUpdate&&["draft","building"].includes(item.status)?<form className="grid gap-4 md:grid-cols-[1fr_14rem_auto]" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);add.mutate({house_forwarding_job_id:Number(data.get("house_forwarding_job_id")),house_reference:data.get("house_reference")||null});}}><Field><FieldLabel htmlFor="house-job">{t("logistics.fields.house_job")}</FieldLabel><NativeSelect id="house-job" name="house_forwarding_job_id" required><option value="">{t("common.select")}</option>{jobs.data?.filter((job)=>job.id!==item.master_forwarding_job_id&&!memberIds.has(job.id)).map((job)=><option key={job.id} value={job.id}>{job.job_number} — {job.customer?.name}</option>)}</NativeSelect></Field><Field><FieldLabel htmlFor="house-reference">{t("logistics.fields.house_reference")}</FieldLabel><Input id="house-reference" name="house_reference" /></Field><Button type="submit" className="min-h-11 self-end" disabled={add.isPending}><Plus aria-hidden="true"/>{t("logistics.actions.add_member")}</Button></form>:null}
  {item.members?.length?<div className="overflow-x-auto"><Table><caption className="sr-only">{t("logistics.consolidations.members")}</caption><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.house_job")}</TableHead><TableHead scope="col">{t("logistics.fields.customer")}</TableHead><TableHead scope="col">{t("logistics.fields.weight")}</TableHead><TableHead scope="col">{t("logistics.fields.volume")}</TableHead><TableHead scope="col">{t("logistics.fields.allocation_percentage")}</TableHead>{canUpdate?<TableHead scope="col"><span className="sr-only">{t("logistics.actions.remove_leg")}</span></TableHead>:null}</TableRow></TableHeader><TableBody>{item.members.map((member)=><TableRow key={member.id}><TableCell><Link href={`/dashboard/logistics/jobs/${member.job?.id??member.house_forwarding_job_id}`} className="font-mono text-primary hover:underline">{member.job?.job_number??member.house_reference??member.house_forwarding_job_id}</Link></TableCell><TableCell>{member.customer?.name??"—"}</TableCell><TableCell>{member.allocated_weight_kg}</TableCell><TableCell>{member.allocated_cbm}</TableCell><TableCell>{member.allocation_percentage}%</TableCell>{canUpdate&&["draft","building"].includes(item.status)?<TableCell><Button type="button" variant="ghost" size="icon" className="min-h-11 min-w-11 text-destructive" aria-label={`${t("logistics.actions.remove_leg")} ${member.job?.job_number??member.id}`} onClick={()=>remove.mutate(member.id)} disabled={remove.isPending}><Trash2 aria-hidden="true"/></Button></TableCell>:null}</TableRow>)}</TableBody></Table></div>:<p className="text-sm text-muted-foreground">{t("logistics.empty.members")}</p>}</CardContent></Card></main>;
}

function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
