"use client";

import Link from "next/link";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Check, CopyPlus, FileCheck2, Send, Ship, X } from "lucide-react";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { NativeSelect } from "@/components/ui/native-select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { usePermissions } from "@/hooks/use-permissions";
import { logisticsApi } from "@/modules/logistics/api";
import type { FreightQuotation } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

type ActionName = "submit" | "send" | "accept" | "reject" | "convert" | "revise";

export default function LogisticsQuotationDetailPage({ quotationId }: { quotationId: string }) {
  const id = Number(quotationId); const { t } = useTranslation(); const cache = useQueryClient(); const { hasAnyPermission } = usePermissions();
  const [actionError, setActionError] = React.useState(""); const [decision, setDecision] = React.useState<"accept"|"reject"|null>(null);
  const query = useQuery({ queryKey: ["logistics", "quotation", id], queryFn: () => logisticsApi.quotation(id).then((response) => response.data.data as FreightQuotation), enabled: Number.isInteger(id) });
  const mutation = useMutation({ mutationFn: ({name,payload}:{name:ActionName;payload?:Record<string,unknown>}) => { const revisionId = query.data?.revision?.id; if (!revisionId && name !== "revise") throw new Error("missing revision"); switch(name){case "submit":return logisticsApi.submitQuotation(id,revisionId!);case "send":return logisticsApi.sendQuotation(id,revisionId!);case "accept":return logisticsApi.acceptQuotation(id,revisionId!,payload??{});case "reject":return logisticsApi.rejectQuotation(id,revisionId!,payload??{});case "convert":return logisticsApi.convertQuotation(id,revisionId!);case "revise":return logisticsApi.reviseQuotation(id);}}, onSuccess: async (response,variables) => { await cache.invalidateQueries({queryKey:["logistics","quotation",id]}); setDecision(null); const bookingId=response.data?.data?.id; if(variables.name==="convert"&&bookingId){window.location.assign(`/dashboard/logistics/bookings/${bookingId}`);return;} toast.success(t(`logistics.quotations.${variables.name}_success`)); }, onError:(value:{response?:{data?:{message?:string}}})=>setActionError(value.response?.data?.message??t("logistics.errors.action")) });
  if (query.isLoading) return <div role="status" className="flex items-center gap-2"><Spinner />{t("logistics.loading")}</div>;
  if (query.isError || !query.data?.revision) return <Alert variant="destructive"><AlertTitle>{t("logistics.errors.load_title")}</AlertTitle><AlertDescription>{t("logistics.errors.quotation")}</AlertDescription></Alert>;
  const quotation=query.data, revision=quotation.revision!, status=revision.status;
  const permissions={submit:hasAnyPermission(["submit_logistics_quotations","manage_logistics"]),send:hasAnyPermission(["send_logistics_quotations","manage_logistics"]),record:hasAnyPermission(["record_logistics_quotation_acceptance","manage_logistics"]),convert:hasAnyPermission(["create_logistics_bookings","manage_logistics"]),revise:hasAnyPermission(["update_logistics_quotations","manage_logistics"])};
  const act=(name:ActionName,payload?:Record<string,unknown>)=>{setActionError("");mutation.mutate({name,payload});};
  return <main className="flex flex-col gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div className="flex flex-col gap-2"><Button variant="link" asChild className="h-auto justify-start p-0"><Link href="/dashboard/logistics/quotations"><ArrowLeft data-icon="inline-start" aria-hidden="true" />{t("logistics.actions.back_quotations")}</Link></Button><div className="flex flex-wrap items-center gap-3"><h1 className="font-mono text-3xl font-black tracking-tight">{quotation.quotation_number}</h1><Badge variant={status==="accepted"?"default":"secondary"}>{t(`logistics.status.${status}`)}</Badge></div><p className="text-sm text-muted-foreground">{quotation.customer?.name} · {revision.origin_node?.name} → {revision.destination_node?.name} · {t("logistics.fields.revision")} {revision.revision}</p></div><div className="flex flex-wrap gap-2">{permissions.revise&&["draft","approved","sent"].includes(status)?<Button variant="outline" onClick={()=>act("revise")} disabled={mutation.isPending}><CopyPlus data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.new_revision")}</Button>:null}{permissions.submit&&status==="draft"?<Button onClick={()=>act("submit")} disabled={mutation.isPending}><FileCheck2 data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.submit_approval")}</Button>:null}{permissions.send&&status==="approved"?<Button onClick={()=>act("send")} disabled={mutation.isPending}><Send data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.mark_sent")}</Button>:null}{permissions.record&&["approved","sent"].includes(status)?<><Button onClick={()=>setDecision("accept")}><Check data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.record_acceptance")}</Button><Button variant="outline" onClick={()=>setDecision("reject")}><X data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.record_rejection")}</Button></>:null}{permissions.convert&&status==="accepted"?<Button onClick={()=>act("convert")} disabled={mutation.isPending}><Ship data-icon="inline-start" aria-hidden="true"/>{t("logistics.actions.convert_booking")}</Button>:null}</div></header>
    {actionError?<Alert variant="destructive"><AlertTitle>{t("logistics.errors.action_title")}</AlertTitle><AlertDescription>{actionError}</AlertDescription></Alert>:null}
    {decision?<Card><CardHeader><CardTitle>{decision==="accept"?t("logistics.quotations.record_acceptance"):t("logistics.quotations.record_rejection")}</CardTitle><CardDescription>{t("logistics.quotations.decision_description")}</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);act(decision,{quotation_option_id:decision==="accept"?Number(data.get("quotation_option_id")):null,acceptance_source:"staff_recorded",notes:data.get("notes")});}}><FieldGroup>{decision==="accept"?<Field><FieldLabel htmlFor="decision-option">{t("logistics.fields.accepted_option")}</FieldLabel><NativeSelect id="decision-option" name="quotation_option_id" required>{revision.options.map((option)=><option key={option.id} value={option.id}>{option.option_code} — {option.label}</option>)}</NativeSelect></Field>:null}<Field><FieldLabel htmlFor="decision-notes">{t("logistics.fields.notes")}</FieldLabel><Textarea id="decision-notes" name="notes" required={decision==="reject"}/></Field></FieldGroup><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setDecision(null)}>{t("common.cancel")}</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?<Spinner data-icon="inline-start"/>:decision==="accept"?<Check data-icon="inline-start" aria-hidden="true"/>:<X data-icon="inline-start" aria-hidden="true"/>}{decision==="accept"?t("logistics.actions.confirm_acceptance"):t("logistics.actions.confirm_rejection")}</Button></div></form></CardContent></Card>:null}
    <Tabs defaultValue="overview"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="overview">{t("logistics.detail.overview")}</TabsTrigger><TabsTrigger value="cargo">{t("logistics.detail.cargo")}</TabsTrigger><TabsTrigger value="route">{t("logistics.detail.route")}</TabsTrigger><TabsTrigger value="pricing">{t("logistics.quotations.pricing")}</TabsTrigger><TabsTrigger value="revisions">{t("logistics.quotations.revisions")}</TabsTrigger><TabsTrigger value="activity">{t("logistics.detail.activity")}</TabsTrigger></TabsList>
      <TabsContent value="overview"><Card><CardHeader><CardTitle>{t("logistics.quotations.summary")}</CardTitle><CardDescription>{t("logistics.quotations.summary_description")}</CardDescription></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase text-muted-foreground">{t("logistics.fields.customer")}</dt><dd className="font-semibold">{quotation.customer?.name}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">{t("logistics.fields.service")}</dt><dd className="font-semibold">{revision.service_type??"—"}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">{t("logistics.fields.valid_until")}</dt><dd className="font-semibold">{revision.valid_until}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">{t("logistics.fields.total_sell")}</dt><dd className="font-semibold">{revision.currency} {revision.total_sell}</dd></div>{revision.margin_percentage!==undefined?<div><dt className="text-xs uppercase text-muted-foreground">{t("logistics.fields.margin")}</dt><dd className="font-semibold">{revision.margin_percentage??"—"}%</dd></div>:null}</dl></CardContent></Card></TabsContent>
      <TabsContent value="cargo"><Card><CardHeader><CardTitle>{t("logistics.detail.cargo")}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table><caption className="sr-only">{t("logistics.quotations.cargo_caption")}</caption><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.description")}</TableHead><TableHead scope="col">{t("logistics.fields.quantity")}</TableHead><TableHead scope="col">{t("logistics.fields.weight")}</TableHead><TableHead scope="col">{t("logistics.fields.volume")}</TableHead></TableRow></TableHeader><TableBody>{revision.cargo.map((item,index)=><TableRow key={String(item.id??index)}><TableCell>{String(item.description??"—")}</TableCell><TableCell>{String(item.quantity??"—")}</TableCell><TableCell>{String(item.gross_weight??"—")}</TableCell><TableCell>{String(item.volume_cbm??"—")}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="route"><div className="grid gap-4 lg:grid-cols-2">{revision.options.map((option)=><Card key={option.id}><CardHeader><CardTitle>{option.option_code} · {option.label}</CardTitle><CardDescription>{option.primary_transport_mode?.name??"—"} · {option.service_type??"—"}</CardDescription></CardHeader><CardContent><ol className="flex flex-col gap-0">{option.legs.map((leg,index)=><li key={leg.id} className="grid grid-cols-[2rem_minmax(0,1fr)] gap-3"><div className="flex flex-col items-center"><span className="grid size-8 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{leg.sequence}</span>{index<option.legs.length-1?<span className="h-10 w-px bg-border" aria-hidden="true"/>:null}</div><div><p className="font-semibold">{leg.origin_node?.name??leg.origin_node_id} → {leg.destination_node?.name??leg.destination_node_id}</p><p className="text-sm text-muted-foreground">{leg.transport_mode?.name??"—"}</p></div></li>)}</ol></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="pricing"><div className="flex flex-col gap-4">{revision.options.map((option)=><Card key={option.id}><CardHeader><CardTitle>{option.option_code} · {option.label}</CardTitle><CardDescription>{revision.currency} {option.total_sell}{option.margin_percentage!==undefined?` · ${t("logistics.fields.margin")} ${option.margin_percentage??"—"}%`:""}</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><Table><caption className="sr-only">{t("logistics.quotations.lines_caption",undefined,{option:option.option_code})}</caption><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.charge_code")}</TableHead><TableHead scope="col">{t("logistics.fields.basis")}</TableHead><TableHead scope="col">{t("logistics.fields.quantity")}</TableHead>{option.lines.some((line)=>line.buy_amount!==undefined)?<TableHead scope="col">{t("logistics.fields.buy_amount")}</TableHead>:null}<TableHead scope="col">{t("logistics.fields.sell_amount")}</TableHead></TableRow></TableHeader><TableBody>{option.lines.map((line)=><TableRow key={line.id}><TableCell>{line.charge_code}<div className="text-xs text-muted-foreground">{line.description}</div></TableCell><TableCell>{t(`logistics.rate_basis.${line.basis}`)}</TableCell><TableCell>{line.quantity}</TableCell>{line.buy_amount!==undefined?<TableCell>{line.currency} {line.buy_amount}</TableCell>:null}<TableCell>{line.currency} {line.sell_amount}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="revisions"><Card><CardHeader><CardTitle>{t("logistics.quotations.revisions")}</CardTitle><CardDescription>{t("logistics.quotations.revisions_description")}</CardDescription></CardHeader><CardContent><ol className="flex flex-col gap-3">{quotation.revision_history?.map((item)=><li key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><span>{t("logistics.fields.revision")} {item.revision} · {item.valid_until}</span><span className="flex items-center gap-2"><span>{item.currency} {item.total_sell}</span><Badge variant="secondary">{t(`logistics.status.${item.status}`)}</Badge></span></li>)}</ol></CardContent></Card></TabsContent>
      <TabsContent value="activity"><Card><CardHeader><CardTitle>{t("logistics.detail.activity")}</CardTitle></CardHeader><CardContent>{quotation.activity?.length?<ol className="flex flex-col gap-3">{quotation.activity.map((item)=><li key={item.id} className="border-l-2 border-primary pl-4"><p className="font-medium">{item.description}</p><time dateTime={item.created_at} className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</time></li>)}</ol>:<p className="text-sm text-muted-foreground">{t("logistics.empty.activity")}</p>}</CardContent></Card></TabsContent>
    </Tabs></main>;
}
