"use client";

import Link from "next/link"; import * as React from "react"; import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"; import { FileCheck2, Plus, Search } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"; import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"; import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"; import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"; import { Input } from "@/components/ui/input"; import { NativeSelect } from "@/components/ui/native-select"; import { Spinner } from "@/components/ui/spinner"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { usePermissions } from "@/hooks/use-permissions"; import { logisticsApi } from "@/modules/logistics/api"; import type { DocumentType, ForwardingJob, FreightDocument } from "@/modules/logistics/types"; import { useTranslation } from "@/store/use-translation";

export default function LogisticsDocumentsPage() {
  const { t } = useTranslation(); const cache = useQueryClient(); const { hasAnyPermission } = usePermissions(); const canCreate = hasAnyPermission(["create_logistics_documents", "manage_logistics"]); const [search, setSearch] = React.useState(""); const [message, setMessage] = React.useState("");
  const query = useQuery({ queryKey: ["logistics", "documents", search], queryFn: () => logisticsApi.documents({ search: search || undefined }).then((r) => r.data) });
  const jobs = useQuery({ queryKey: ["logistics", "jobs", "documents"], queryFn: () => logisticsApi.jobs({ per_page: 100 }).then((r) => (r.data.data ?? []) as ForwardingJob[]) });
  const types = useQuery({ queryKey: ["logistics", "document-types"], queryFn: () => logisticsApi.documentTypes().then((r) => (r.data.data ?? []) as DocumentType[]) });
  const create = useMutation({ mutationFn: (payload: Record<string, unknown>) => logisticsApi.createDocument(payload), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["logistics", "documents"] }); setMessage(t("logistics.messages.document_created")); }, onError: () => setMessage(t("logistics.errors.document_save")) });
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const d = new FormData(e.currentTarget); create.mutate({ forwarding_job_id: Number(d.get("forwarding_job_id")), document_type_id: Number(d.get("document_type_id")), document_number: d.get("document_number") || null, issuer_name_snapshot: d.get("issuer") || null, source: "uploaded", original_copy: d.get("original_copy") }); };
  const items = (query.data?.data ?? []) as FreightDocument[];
  return <main className="flex flex-col gap-6"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{t("logistics.eyebrow")}</p><h1 className="text-3xl font-black tracking-tight">{t("logistics.documents.title")}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{t("logistics.documents.subtitle")}</p></header><div aria-live="polite">{message ? <Alert><AlertTitle>{message}</AlertTitle></Alert> : null}</div>
    {canCreate ? <details className="rounded-2xl border bg-card p-5"><summary className="flex min-h-11 cursor-pointer items-center gap-2 font-bold"><Plus aria-hidden="true" />{t("logistics.documents.create")}</summary><p className="mt-2 text-sm text-muted-foreground">{t("logistics.documents.create_description")}</p><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field><FieldLabel htmlFor="document-job">{t("logistics.fields.job")}</FieldLabel><NativeSelect id="document-job" name="forwarding_job_id" required><option value="">{t("common.select")}</option>{jobs.data?.map((job) => <option key={job.id} value={job.id}>{job.job_number}</option>)}</NativeSelect></Field><Field><FieldLabel htmlFor="document-type">{t("logistics.fields.document_type")}</FieldLabel><NativeSelect id="document-type" name="document_type_id" required><option value="">{t("common.select")}</option>{types.data?.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</NativeSelect></Field><Field><FieldLabel htmlFor="document-number">{t("logistics.fields.document_number")}</FieldLabel><Input id="document-number" name="document_number" /></Field><Field><FieldLabel htmlFor="document-issuer">{t("logistics.fields.issuer")}</FieldLabel><Input id="document-issuer" name="issuer" /></Field><Field><FieldLabel htmlFor="document-copy">{t("logistics.fields.copy_type")}</FieldLabel><NativeSelect id="document-copy" name="original_copy" defaultValue="copy"><option value="copy">{t("logistics.documents.copy")}</option><option value="original">{t("logistics.documents.original")}</option></NativeSelect></Field><Button type="submit" className="min-h-11 self-end" disabled={create.isPending}>{create.isPending ? <Spinner /> : <FileCheck2 aria-hidden="true" />}{t("logistics.actions.create_document")}</Button></form></details> : null}
    <Card><CardHeader><CardTitle>{t("logistics.documents.directory")}</CardTitle><CardDescription>{t("logistics.documents.directory_description")}</CardDescription></CardHeader><CardContent className="space-y-4"><Field><FieldLabel htmlFor="document-search">{t("logistics.fields.search")}</FieldLabel><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-5 text-muted-foreground" aria-hidden="true" /><Input id="document-search" className="pl-10" value={search} onChange={(e) => setSearch(e.target.value)} /></div></Field>{query.isLoading ? <div role="status" className="flex items-center gap-2"><Spinner />{t("logistics.loading")}</div> : query.isError ? <Alert variant="destructive"><AlertTitle>{t("logistics.errors.load_title")}</AlertTitle><AlertDescription>{t("logistics.errors.documents")}</AlertDescription></Alert> : items.length === 0 ? <Empty><EmptyHeader><EmptyMedia variant="icon"><FileCheck2 aria-hidden="true" /></EmptyMedia><EmptyTitle>{t("logistics.empty.documents_title")}</EmptyTitle><EmptyDescription>{t("logistics.empty.documents_description")}</EmptyDescription></EmptyHeader></Empty> : <div className="overflow-x-auto"><Table><caption className="sr-only">{t("logistics.documents.caption")}</caption><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.document")}</TableHead><TableHead scope="col">{t("logistics.fields.document_type")}</TableHead><TableHead scope="col">{t("logistics.fields.job")}</TableHead><TableHead scope="col">{t("logistics.fields.version")}</TableHead><TableHead scope="col">{t("logistics.fields.status")}</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell><Button variant="link" asChild className="px-0 font-mono"><Link href={`/dashboard/logistics/documents/${item.id}`}>{item.document_number ?? item.document_record_number}</Link></Button></TableCell><TableCell>{item.type?.name ?? "—"}</TableCell><TableCell>{item.job?.job_number ?? "—"}</TableCell><TableCell>{item.current_version}</TableCell><TableCell><Badge variant={item.status === "issued" ? "default" : "secondary"}>{t(`logistics.status.${item.status}`)}</Badge></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card></main>;
}
