"use client";

import Link from "next/link";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Combine, Plus, Search } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { usePermissions } from "@/hooks/use-permissions";
import { logisticsApi } from "@/modules/logistics/api";
import type { Consolidation, ForwardingJob, LogisticsReferences } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

const ALLOCATION_METHODS=["weight","cbm","chargeable_weight","packages","equal","manual"];

export default function LogisticsConsolidationsPage(){
  const{t}=useTranslation();const cache=useQueryClient();const{hasAnyPermission}=usePermissions();const canCreate=hasAnyPermission(["create_logistics_consolidations","manage_logistics"]);
  const[search,setSearch]=React.useState("");const[status,setStatus]=React.useState("");const[notice,setNotice]=React.useState("");const[error,setError]=React.useState("");
  const query=useQuery({queryKey:["logistics","consolidations",search,status],queryFn:()=>logisticsApi.consolidations({search:search||undefined,status:status||undefined}).then((response)=>response.data)});
  const refs=useQuery({queryKey:["logistics","references"],queryFn:()=>logisticsApi.references().then((response)=>response.data.data as LogisticsReferences)});
  const jobs=useQuery({queryKey:["logistics","jobs","consolidation"],queryFn:()=>logisticsApi.jobs({per_page:100}).then((response)=>(response.data.data??[]) as ForwardingJob[])});
  const create=useMutation({mutationFn:(payload:Record<string,unknown>)=>logisticsApi.createConsolidation(payload),onSuccess:async()=>{await cache.invalidateQueries({queryKey:["logistics","consolidations"]});setError("");setNotice(t("logistics.messages.consolidation_created"));},onError:(value:unknown)=>setError((value as {response?:{data?:{message?:string}}}).response?.data?.message??t("logistics.errors.consolidation_save"))});
  const items=(query.data?.data??[]) as Consolidation[];
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const optionalNumber=(name:string)=>data.get(name)?Number(data.get(name)):null;create.mutate({master_reference:data.get("master_reference")||null,master_forwarding_job_id:optionalNumber("master_forwarding_job_id"),transport_mode_id:Number(data.get("transport_mode_id")),provider_supplier_id:optionalNumber("provider_supplier_id"),origin_node_id:Number(data.get("origin_node_id")),destination_node_id:Number(data.get("destination_node_id")),allocation_method:data.get("allocation_method"),capacity_weight_kg:data.get("capacity_weight_kg")||null,capacity_cbm:data.get("capacity_cbm")||null,capacity_packages:data.get("capacity_packages")||null,planned_departure_at:data.get("planned_departure_at")||null,planned_arrival_at:data.get("planned_arrival_at")||null});};
  return <main className="flex flex-col gap-6"><header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{t("logistics.eyebrow")}</p><h1 className="text-3xl font-black tracking-tight">{t("logistics.consolidations.title")}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{t("logistics.consolidations.subtitle")}</p></header>
  <div aria-live="polite">{notice?<Alert><AlertTitle>{notice}</AlertTitle></Alert>:null}{error?<Alert variant="destructive"><AlertTitle>{t("logistics.errors.action_title")}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>:null}</div>
  {canCreate?<details className="rounded-2xl border bg-card p-5"><summary className="flex min-h-11 cursor-pointer items-center gap-2 font-bold"><Plus aria-hidden="true"/>{t("logistics.consolidations.create")}</summary><p className="mt-2 text-sm text-muted-foreground">{t("logistics.consolidations.create_description")}</p><form className="mt-4 grid gap-4 md:grid-cols-3" onSubmit={submit}>
    <Field><FieldLabel htmlFor="consolidation-reference">{t("logistics.fields.master_reference")}</FieldLabel><Input id="consolidation-reference" name="master_reference" /></Field>
    <Field><FieldLabel htmlFor="consolidation-master-job">{t("logistics.fields.master_job")}</FieldLabel><NativeSelect id="consolidation-master-job" name="master_forwarding_job_id"><option value="">{t("logistics.optional.none")}</option>{jobs.data?.map((job)=><option key={job.id} value={job.id}>{job.job_number} — {job.customer?.name}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-mode">{t("logistics.fields.mode")}</FieldLabel><NativeSelect id="consolidation-mode" name="transport_mode_id" required><option value="">{t("common.select")}</option>{refs.data?.modes.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-origin">{t("logistics.fields.origin")}</FieldLabel><NativeSelect id="consolidation-origin" name="origin_node_id" required><option value="">{t("common.select")}</option>{refs.data?.nodes.map((item)=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-destination">{t("logistics.fields.destination")}</FieldLabel><NativeSelect id="consolidation-destination" name="destination_node_id" required><option value="">{t("common.select")}</option>{refs.data?.nodes.map((item)=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-provider">{t("logistics.fields.provider")}</FieldLabel><NativeSelect id="consolidation-provider" name="provider_supplier_id"><option value="">{t("logistics.optional.any_provider")}</option>{refs.data?.suppliers.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-allocation">{t("logistics.fields.allocation_method")}</FieldLabel><NativeSelect id="consolidation-allocation" name="allocation_method" defaultValue="cbm">{ALLOCATION_METHODS.map((value)=><option key={value} value={value}>{t(`logistics.allocation.${value}`)}</option>)}</NativeSelect></Field>
    <Field><FieldLabel htmlFor="consolidation-weight-capacity">{t("logistics.fields.capacity_weight")}</FieldLabel><Input id="consolidation-weight-capacity" name="capacity_weight_kg" type="number" min="0" step="0.001" /></Field>
    <Field><FieldLabel htmlFor="consolidation-cbm-capacity">{t("logistics.fields.capacity_cbm")}</FieldLabel><Input id="consolidation-cbm-capacity" name="capacity_cbm" type="number" min="0" step="0.001" /></Field>
    <Field><FieldLabel htmlFor="consolidation-package-capacity">{t("logistics.fields.capacity_packages")}</FieldLabel><Input id="consolidation-package-capacity" name="capacity_packages" type="number" min="0" step="1" /></Field>
    <Field><FieldLabel htmlFor="consolidation-departure">{t("logistics.fields.departure")}</FieldLabel><Input id="consolidation-departure" name="planned_departure_at" type="datetime-local" /></Field>
    <Field><FieldLabel htmlFor="consolidation-arrival">{t("logistics.fields.arrival")}</FieldLabel><Input id="consolidation-arrival" name="planned_arrival_at" type="datetime-local" /></Field>
    <Button type="submit" className="min-h-11 self-end md:justify-self-end" disabled={create.isPending}>{create.isPending?<Spinner/>:<Combine aria-hidden="true"/>}{t("logistics.actions.create_consolidation")}</Button>
  </form></details>:null}
  <Card><CardHeader><CardTitle>{t("logistics.consolidations.directory")}</CardTitle><CardDescription>{t("logistics.consolidations.directory_description")}</CardDescription></CardHeader><CardContent className="space-y-4"><FieldGroup className="grid md:grid-cols-[minmax(16rem,1fr)_14rem]"><Field><FieldLabel htmlFor="consolidation-search">{t("logistics.fields.search")}</FieldLabel><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-5 text-muted-foreground" aria-hidden="true"/><Input id="consolidation-search" className="pl-10" value={search} onChange={(event)=>setSearch(event.target.value)}/></div></Field><Field><FieldLabel htmlFor="consolidation-status">{t("logistics.fields.status")}</FieldLabel><NativeSelect id="consolidation-status" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">{t("logistics.status.all")}</option>{["draft","building","ready","confirmed","in_transit","arrived","deconsolidating","completed","cancelled"].map((value)=><option key={value} value={value}>{t(`logistics.status.${value}`,value.replaceAll("_"," "))}</option>)}</NativeSelect></Field></FieldGroup>
  {query.isLoading?<div role="status" className="flex items-center gap-2"><Spinner/>{t("logistics.loading")}</div>:query.isError?<Alert variant="destructive"><AlertTitle>{t("logistics.errors.load_title")}</AlertTitle><AlertDescription>{t("logistics.errors.consolidations")}</AlertDescription></Alert>:items.length===0?<Empty><EmptyHeader><EmptyMedia variant="icon"><Combine aria-hidden="true"/></EmptyMedia><EmptyTitle>{t("logistics.empty.consolidations_title")}</EmptyTitle><EmptyDescription>{t("logistics.empty.consolidations_description")}</EmptyDescription></EmptyHeader></Empty>:<div className="overflow-x-auto"><Table><caption className="sr-only">{t("logistics.consolidations.caption")}</caption><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.master_reference")}</TableHead><TableHead scope="col">{t("logistics.fields.mode")}</TableHead><TableHead scope="col">{t("logistics.fields.route")}</TableHead><TableHead scope="col">{t("logistics.fields.members")}</TableHead><TableHead scope="col">{t("logistics.fields.departure")}</TableHead><TableHead scope="col">{t("logistics.fields.status")}</TableHead></TableRow></TableHeader><TableBody>{items.map((item)=><TableRow key={item.id}><TableCell><Button variant="link" asChild className="px-0 font-mono"><Link href={`/dashboard/logistics/consolidations/${item.id}`}>{item.consolidation_number}</Link></Button><p className="text-xs text-muted-foreground">{item.master_reference??"—"}</p></TableCell><TableCell>{item.mode?.name??"—"}</TableCell><TableCell>{item.origin_node?.code??"—"} → {item.destination_node?.code??"—"}</TableCell><TableCell>{item.members_count??item.members?.length??0}</TableCell><TableCell>{item.planned_departure_at?new Date(item.planned_departure_at).toLocaleString():"—"}</TableCell><TableCell><Badge variant={item.status==="in_transit"?"default":"secondary"}>{t(`logistics.status.${item.status}`,item.status.replaceAll("_"," "))}</Badge></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card></main>;
}
