"use client";

import Link from "next/link";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Download, FileOutput, FileUp } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { usePermissions } from "@/hooks/use-permissions";
import { logisticsApi } from "@/modules/logistics/api";
import type { FreightDocument } from "@/modules/logistics/types";
import { useTranslation } from "@/store/use-translation";

const nextStatuses: Record<string, string[]> = { draft: ["cancelled"], generated: ["pending_review", "issued", "superseded", "cancelled"], uploaded: ["pending_review", "issued", "superseded", "cancelled"], pending_review: ["approved", "rejected", "cancelled"], approved: ["issued", "superseded", "expired"], issued: ["superseded", "expired"], rejected: ["uploaded", "generated", "cancelled"] };

export default function LogisticsDocumentDetailPage({ documentId }: { documentId: string }) {
  const { t } = useTranslation(); const cache = useQueryClient(); const { hasAnyPermission } = usePermissions(); const [message, setMessage] = React.useState("");
  const canUpload = hasAnyPermission(["update_logistics_documents", "manage_logistics"]); const canApprove = hasAnyPermission(["approve_logistics_documents", "manage_logistics"]); const canIssue = hasAnyPermission(["issue_logistics_documents", "manage_logistics"]); const canDownload = hasAnyPermission(["download_logistics_documents", "manage_logistics"]);
  const query = useQuery({ queryKey: ["logistics", "documents", documentId], queryFn: () => logisticsApi.document(documentId).then((r) => r.data.data as FreightDocument) });
  const refresh = async () => { await cache.invalidateQueries({ queryKey: ["logistics", "documents", documentId] }); await cache.invalidateQueries({ queryKey: ["logistics", "documents"] }); };
  const upload = useMutation({ mutationFn: (payload: FormData) => logisticsApi.uploadDocumentVersion(documentId, payload), onSuccess: async () => { await refresh(); setMessage(t("logistics.messages.document_version_uploaded")); }, onError: () => setMessage(t("logistics.errors.document_save")) });
  const generate = useMutation({ mutationFn: (reason: string) => logisticsApi.generateDocumentVersion(documentId, reason), onSuccess: async () => { await refresh(); setMessage(t("logistics.messages.document_version_generated")); }, onError: () => setMessage(t("logistics.errors.document_save")) });
  const transition = useMutation({ mutationFn: (status: string) => logisticsApi.transitionDocument(documentId, status), onSuccess: async () => { await refresh(); setMessage(t("logistics.messages.document_updated")); }, onError: () => setMessage(t("logistics.errors.document_save")) });
  const download = async (versionId: number, filename: string | null) => { try { const response = await logisticsApi.downloadDocumentVersion(documentId, versionId); const url = URL.createObjectURL(response.data); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = filename || `freight-document-v${versionId}`; anchor.click(); URL.revokeObjectURL(url); } catch { setMessage(t("logistics.errors.document_save")); } };
  if (query.isLoading) return <div role="status" className="flex items-center gap-2"><Spinner />{t("logistics.loading")}</div>;
  if (query.isError || !query.data) return <Alert variant="destructive"><AlertTitle>{t("logistics.errors.document_load_title")}</AlertTitle><AlertDescription>{t("logistics.errors.documents")}</AlertDescription></Alert>;
  const item = query.data; const transitions = (nextStatuses[item.status] ?? []).filter((status) => status === "approved" || status === "rejected" ? canApprove : status === "issued" ? canIssue : canUpload);
  return <main className="flex flex-col gap-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" asChild className="-ml-3 min-h-11"><Link href="/dashboard/logistics/documents"><ArrowLeft aria-hidden="true" />{t("logistics.actions.back_documents")}</Link></Button><p className="mt-2 font-mono text-sm text-muted-foreground">{item.document_record_number}</p><h1 className="text-3xl font-black tracking-tight">{item.document_number ?? item.type?.name ?? t("logistics.documents.overview")}</h1></div><Badge className="mt-3" variant={item.status === "issued" ? "default" : "secondary"}>{t(`logistics.status.${item.status}`)}</Badge></header>
    <div aria-live="polite">{message ? <Alert><AlertTitle>{message}</AlertTitle></Alert> : null}</div>
    <Card><CardContent className="grid gap-4 pt-6 sm:grid-cols-2 lg:grid-cols-4"><Datum label={t("logistics.fields.document_type")} value={item.type?.name} /><Datum label={t("logistics.fields.job")} value={item.job?.job_number} /><Datum label={t("logistics.fields.copy_type")} value={item.original_copy} /><Datum label={t("logistics.fields.version")} value={String(item.current_version)} /></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-2">{canUpload ? <Card><CardHeader><CardTitle>{t("logistics.documents.upload")}</CardTitle><CardDescription>{t("logistics.documents.upload_description")}</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(e) => { e.preventDefault(); upload.mutate(new FormData(e.currentTarget)); }} encType="multipart/form-data"><Field><FieldLabel htmlFor="document-file">{t("logistics.fields.file")}</FieldLabel><Input id="document-file" name="file" type="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.webp,.txt,.xml" /></Field><Field><FieldLabel htmlFor="document-change-reason">{t("logistics.fields.change_reason")}</FieldLabel><Input id="document-change-reason" name="change_reason" required /></Field><Button className="min-h-11 justify-self-start" disabled={upload.isPending}>{upload.isPending ? <Spinner /> : <FileUp aria-hidden="true" />}{t("logistics.actions.upload_version")}</Button></form></CardContent></Card> : null}
      <div className="space-y-6">{canUpload && item.type?.code === "manifest" ? <Card><CardHeader><CardTitle>{t("logistics.documents.generate")}</CardTitle><CardDescription>{t("logistics.documents.generate_description")}</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-4 sm:flex-row sm:items-end" onSubmit={(e) => { e.preventDefault(); generate.mutate(String(new FormData(e.currentTarget).get("change_reason"))); }}><Field className="flex-1"><FieldLabel htmlFor="document-generate-reason">{t("logistics.fields.change_reason")}</FieldLabel><Input id="document-generate-reason" name="change_reason" required defaultValue={t("logistics.documents.generated_reason")} /></Field><Button className="min-h-11" disabled={generate.isPending}>{generate.isPending ? <Spinner /> : <FileOutput aria-hidden="true" />}{t("logistics.actions.generate_manifest")}</Button></form></CardContent></Card> : null}{transitions.length ? <Card><CardHeader><CardTitle>{t("logistics.actions.update_document_status")}</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-4 sm:flex-row sm:items-end" onSubmit={(e) => { e.preventDefault(); transition.mutate(String(new FormData(e.currentTarget).get("status"))); }}><Field className="flex-1"><FieldLabel htmlFor="document-status">{t("logistics.fields.status")}</FieldLabel><NativeSelect id="document-status" name="status">{transitions.map((status) => <option key={status} value={status}>{t(`logistics.status.${status}`)}</option>)}</NativeSelect></Field><Button className="min-h-11" disabled={transition.isPending}>{t("logistics.actions.update_document_status")}</Button></form></CardContent></Card> : null}</div></div>
    <Card><CardHeader><CardTitle>{t("logistics.documents.versions")}</CardTitle><CardDescription>{t("logistics.documents.versions_description")}</CardDescription></CardHeader><CardContent>{item.versions?.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead scope="col">{t("logistics.fields.version")}</TableHead><TableHead scope="col">{t("logistics.fields.file")}</TableHead><TableHead scope="col">{t("logistics.fields.file_size")}</TableHead><TableHead scope="col">{t("logistics.fields.change_reason")}</TableHead><TableHead scope="col"><span className="sr-only">{t("logistics.actions.download_version")}</span></TableHead></TableRow></TableHeader><TableBody>{item.versions.map((version) => <TableRow key={version.id}><TableCell>{version.version}</TableCell><TableCell><span className="block max-w-64 truncate" title={version.original_filename ?? undefined}>{version.original_filename ?? "—"}</span><code className="block max-w-64 truncate text-xs text-muted-foreground" title={version.sha256 ?? undefined}>{version.sha256 ?? "—"}</code></TableCell><TableCell>{formatBytes(version.size_bytes)}</TableCell><TableCell>{version.change_reason ?? "—"}</TableCell><TableCell>{canDownload ? <Button variant="outline" className="min-h-11" onClick={() => download(version.id, version.original_filename)}><Download aria-hidden="true" />{t("logistics.actions.download_version")}</Button> : null}</TableCell></TableRow>)}</TableBody></Table></div> : <Empty><EmptyHeader><EmptyTitle>{t("logistics.empty.versions")}</EmptyTitle></EmptyHeader></Empty>}</CardContent></Card>
  </main>;
}

function Datum({ label, value }: { label: string; value?: string | null }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value || "—"}</dd></div>; }
function formatBytes(value: number | null) { if (value === null) return "—"; if (value < 1024) return `${value} B`; if (value < 1048576) return `${(value / 1024).toFixed(1)} KB`; return `${(value / 1048576).toFixed(1)} MB`; }
