import { Barcode, Boxes, ClipboardCheck, Coins, Gauge, Layers, LayoutDashboard, Link2, PackageSearch, Route, Scale, Shapes, SlidersHorizontal, Tags, Truck } from "lucide-react";
import type { FrontendModuleDefinition } from "@/modules/types";

export const inventoryModule: FrontendModuleDefinition = {
  id: "inventory",
  name: "Inventory",
  description: "Enterprise product catalog, stock operations, supplier management, and QA batches.",
  backendModule: "Modules\\Inventory",
  routePrefixes: [
    "/dashboard/inventory",
    "/dashboard/inventory/catalog/products",
    "/dashboard/inventory/catalog/goods",
    "/dashboard/inventory/catalog/categories",
    "/dashboard/inventory/catalog/tags",
    "/dashboard/inventory/catalog/suppliers",
    "/dashboard/inventory/qa",
    "/dashboard/inventory/documents",
    "/dashboard/inventory/serials",
    "/dashboard/inventory/batches",
    "/dashboard/inventory/valuation",
    "/dashboard/inventory/reconciliation",
    "/dashboard/inventory/stocktakes",
    "/dashboard/inventory/overview",
    "/dashboard/inventory/reorder-basis",
    "/dashboard/inventory/gl-trace",
    "/dashboard/inventory/settings/costing",
    "/dashboard/inventory/settings/account-mapping",
  ],
  navItems: [
    {
      moduleId: "inventory",
      translationKey: "nav.inventory",
      fallbackLabel: "Inventory Dashboard",
      href: "/dashboard/inventory",
      icon: LayoutDashboard,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
      tourId: "tour-nav-inventory",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_overview",
      fallbackLabel: "Operations Overview",
      href: "/dashboard/inventory/overview",
      icon: Gauge,
      permissions: ["view_inventory", "manage_inventory", "view_finance"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_products",
      fallbackLabel: "Products",
      href: "/dashboard/inventory/catalog/products",
      icon: PackageSearch,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_goods",
      fallbackLabel: "Goods (Raw Materials)",
      href: "/dashboard/inventory/catalog/goods",
      icon: Boxes,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_categories",
      fallbackLabel: "Product Categories",
      href: "/dashboard/inventory/catalog/categories",
      icon: Shapes,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_tags",
      fallbackLabel: "Product Tags",
      href: "/dashboard/inventory/catalog/tags",
      icon: Tags,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_suppliers",
      fallbackLabel: "Suppliers",
      href: "/dashboard/inventory/catalog/suppliers",
      icon: Truck,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_qa",
      fallbackLabel: "Quality Assurance",
      href: "/dashboard/inventory/qa",
      icon: ClipboardCheck,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      businessTypes: ["water-bottling"],
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_documents",
      fallbackLabel: "Inventory Documents",
      href: "/dashboard/inventory/documents",
      icon: LayoutDashboard,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_batches",
      fallbackLabel: "Batches & Expiry",
      href: "/dashboard/inventory/batches",
      icon: Layers,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_serials",
      fallbackLabel: "Serial Numbers",
      href: "/dashboard/inventory/serials",
      icon: Barcode,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_stocktakes",
      fallbackLabel: "Stocktakes",
      href: "/dashboard/inventory/stocktakes",
      icon: ClipboardCheck,
      permissions: ["view_inventory_counts", "view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_valuation",
      fallbackLabel: "Valuation",
      href: "/dashboard/inventory/valuation",
      icon: Coins,
      permissions: ["view_finance"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_reconciliation",
      fallbackLabel: "Reconciliation",
      href: "/dashboard/inventory/reconciliation",
      icon: Scale,
      permissions: ["view_finance"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_gl_trace",
      fallbackLabel: "GL Trace",
      href: "/dashboard/inventory/gl-trace",
      icon: Route,
      permissions: ["view_finance"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_reorder_basis",
      fallbackLabel: "Reorder Basis",
      href: "/dashboard/inventory/reorder-basis",
      icon: Gauge,
      permissions: ["view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_costing",
      fallbackLabel: "Costing Settings",
      href: "/dashboard/inventory/settings/costing",
      icon: SlidersHorizontal,
      permissions: ["view_finance", "view_inventory", "manage_inventory"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
    {
      moduleId: "inventory",
      translationKey: "nav.inventory_account_mapping",
      fallbackLabel: "Account Mapping",
      href: "/dashboard/inventory/settings/account-mapping",
      icon: Link2,
      permissions: ["view_finance"],
      subscriptionSlug: "inventory_control",
      placement: "primary",
    },
  ],
};
